{% set name = "drafthorse" %}
{% set version = "2025.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drafthorse-{{ version }}.tar.gz
  sha256: 83b0bae0cc72b99fd79c870828af7e20075ce8c60c43ef2c363f24940399db4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - pypdf
    - python >={{ python_min }}
    - lxml

test:
  imports:
    - drafthorse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pretix/python-drafthorse
  summary: Python ZUGFeRD XML implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
